### PR TITLE
Style to match mocks

### PR DESCRIPTION
**Pull request by mattbaker**
@ashanan

### CODE REVIEW

**Comment by ashanan** [comment]
The code looks fine, but there a couple of styling issues:
1. The share buttons are overlapping.

screen shot 2016-11-16 at 11 00 49 am
2. The little flyouts that show up when you submit without an email or message don't really match the style of the rest of the site.  Other than that, this looks good.

**Comment by mattbaker** [comment]
Weiiiiiiiird, I wonder why that didn't trigger on my machine.

**Comment by mattbaker** [comment]
(also, good catch)

**Comment by mattbaker** [comment]
@ashanan — I'm ok with the flyouts, it's easy validation that comes for free from Chrome, even if we can't style it (unless you find otherwise).

Can you demo the FB thing on your computer with me? I can't repro it

**Pull request merged**
